services:
  rovio:
    hostname: gscam_bno055_rp2040
    container_name: gscam_bno055_rp2040
#    image: rrovix:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - user=${USER}
      - uid=1000
      - gid=1000

    environment:
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "DISPLAY=${DISPLAY}"
      - "XAUTHORITY=/tmp/.docker.xauth"

    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth:rw"
      - "/etc/localtime:/etc/localtime:ro" # Монтирование настроек времени
      - /dev/video0:/dev/video0 # Проброс устройства для обработки видео https://foundries.io/insights/blog/sharing-camera-with-docker/

    deploy:
      resources:
        limits:
          cpus: '0.5' # Ограничение в потреблении ресурсов ЦПУ


    devices:
      - "/dev/ttyACM0:/dev/ttyACM0:rw" #Проброс COM-порта для связи с RP2040

    device_cgroup_rules:
      - 'c 89:* rmw' #Установка прав доступа к символьному устройству I2C датчику


    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    #command: "/bin/bash"
