services:
  app:
    hostname: ros_rov
    container_name: rrovixcon
#    image: rrovix:latest
    build:
      context: .
#     dockerfile: Dockerfile
      args:
      - user=${USER}
      - uid=${UIDI:-1000}
      - gid=${GIDI:-1000}
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    deploy:
      resources:
        limits:
          cpus: '0.5' # Ограничение в потреблении ресурсов ЦПУ

    # src to connect with X11 https://wiki.ros.org/docker/Tutorials/GUI#Using_Wayland
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.docker.xauth:/tmp/.docker.xauth:rw
      - .:/opt/ros/overlay_ws/src/rovio/cfg/gopro10
      
    network_mode: host

