services:
  app:
    hostname: ros_rov
    container_name: rrovixcon
#    image: rrovix:latest
    runtime: nvidia  # Поддержка GPU (требуется Docker с поддержкой NVIDIA)
    build:
      context: .
#     dockerfile: Dockerfile
      args:
      - user=${USER}
      - uid=${UID:-1000}
      - gid=${GID:-1000}
    environment:
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}  # Для правильных прав X11
      - NVIDIA_DRIVER_CAPABILITIES=all  # Дает доступ ко всем возможностям GPU
      - NVIDIA_VISIBLE_DEVICES=all  # Делает все GPU видимыми
    deploy:
      resources:
        limits:
          cpus: '0.5' # Ограничение в потреблении ресурсов ЦПУ
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  # Явное резервирование GPU

    tty: true       # Эквивалент -t
    stdin_open: true # Эквивалент -i

    # src to connect with X11 https://wiki.ros.org/docker/Tutorials/GUI#Using_Wayland
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - .:/opt/ros/overlay_ws/src/rovio/cfg/gopro10
      - ../../bags_video_data:/bags_video_data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri  # Для аппаратного ускорения (Intel/AMD)
    network_mode: host
    # command: bash -c "/opt/ros/overlay_ws/src/rovio/cfg/gopro10_docker/entrypoint.sh || bash"
    user: "${UID:-1000}:${GID:-1000}"  # Запуск от текущего пользователя хоста
    command: ["/opt/ros/overlay_ws/src/rovio/cfg/gopro10/entrypoint.sh", "--interactive"]
